spring.application.name=sprinai-demo
spring.ai.openai.apikey=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
spring.ai.openai.imageUrl=https://api.openai.com/v1/images/generations