test:
  region:
    code: "75013"
    name: "fooo"
  name: "yooo"
  pwd: "doooo"
  lastName: "booooo"
spring:
  ai:
    openai:
      apikey: ${OPENAI_API_KEY}
      imageUrl: https://api.openai.com/v1/images/generations
    chat: gpt-4
    request: maxTokens150
    temperature: 0.7
    topP: 1.0
  application:
    name: sprinai-demo



